# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NwfscAllTaxonSubcategories")

model_instance <- NwfscAllTaxonSubcategories$new()

test_that("label", {
  # tests for the property `label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("taxon_category", {
  # tests for the property `taxon_category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_category`, "EXPECTED_RESULT")
})
