# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BottomTrawlBottomTrawlSurveyYears")

model_instance <- BottomTrawlBottomTrawlSurveyYears$new()

test_that("label", {
  # tests for the property `label` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("nmfs_project_names", {
  # tests for the property `nmfs_project_names` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nmfs_project_names`, "EXPECTED_RESULT")
})
