# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HookAndLineHookAndLineCommonNames")

model_instance <- HookAndLineHookAndLineCommonNames$new()

test_that("label", {
  # tests for the property `label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("vessels", {
  # tests for the property `vessels` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`vessels`, "EXPECTED_RESULT")
})

test_that("survey_years", {
  # tests for the property `survey_years` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`survey_years`, "EXPECTED_RESULT")
})
