# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BottomTrawlStationSearches")

model_instance <- BottomTrawlStationSearches$new()

test_that("leg_number", {
  # tests for the property `leg_number` (integer)
  # Leg increment number when a sampling operation took place.  Each vessel participating in the survey partakes in multiple legs (leg #1, #2...) as part of the survey schedule within a given pass, with each survey containing multiple passes per year.  A vessel on the WCGBTS Shelf/Slope Survey typically is scheduled for 5 legs per year, although this is subject to change due to year-to-year schedule differences.

  # uncomment below to test the property
  #expect_equal(model.instance$`leg_number`, "EXPECTED_RESULT")
})

test_that("pass_number", {
  # tests for the property `pass_number` (integer)
  # Pass increment number when a sampling operation took place (i.e. pass #1, #2...).  Each annual survey typically has multiple passes, with each pass being assigned one or several vessels to participate in sampling.

  # uncomment below to test the property
  #expect_equal(model.instance$`pass_number`, "EXPECTED_RESULT")
})

test_that("survey_year", {
  # tests for the property `survey_year` (integer)
  # Calendar year in integer format YYYY during which data was collected.

  # uncomment below to test the property
  #expect_equal(model.instance$`survey_year`, "EXPECTED_RESULT")
})

test_that("vessel_name", {
  # tests for the property `vessel_name` (character)
  # Full name of the commercial or research vessel used to collect the data at sea.

  # uncomment below to test the property
  #expect_equal(model.instance$`vessel_name`, "EXPECTED_RESULT")
})

test_that("captain_name", {
  # tests for the property `captain_name` (character)
  # Full name of the vessel captain.

  # uncomment below to test the property
  #expect_equal(model.instance$`captain_name`, "EXPECTED_RESULT")
})

test_that("search_notes", {
  # tests for the property `search_notes` (character)
  # Notes and field remarks recorded during the station search.

  # uncomment below to test the property
  #expect_equal(model.instance$`search_notes`, "EXPECTED_RESULT")
})

test_that("resulting_tows", {
  # tests for the property `resulting_tows` (object)
  # JSONB array of successfully executed bottom trawl tows resulting from this search.

  # uncomment below to test the property
  #expect_equal(model.instance$`resulting_tows`, "EXPECTED_RESULT")
})

test_that("search_ended_at", {
  # tests for the property `search_ended_at` (character)
  # The timestamp when the search operation ended.

  # uncomment below to test the property
  #expect_equal(model.instance$`search_ended_at`, "EXPECTED_RESULT")
})

test_that("nmfs_project_name", {
  # tests for the property `nmfs_project_name` (character)
  # Name of the project/survey under the National Marine Fisheries Service (NMFS) for which the data was collected.

  # uncomment below to test the property
  #expect_equal(model.instance$`nmfs_project_name`, "EXPECTED_RESULT")
})

test_that("search_started_at", {
  # tests for the property `search_started_at` (character)
  # The timestamp when the search operation started.

  # uncomment below to test the property
  #expect_equal(model.instance$`search_started_at`, "EXPECTED_RESULT")
})

test_that("target_station_code", {
  # tests for the property `target_station_code` (character)
  # Code of the target sampling site station.

  # uncomment below to test the property
  #expect_equal(model.instance$`target_station_code`, "EXPECTED_RESULT")
})

test_that("search_elapsed_time_s", {
  # tests for the property `search_elapsed_time_s` (numeric)
  # The elapsed duration of the search operation in seconds.

  # uncomment below to test the property
  #expect_equal(model.instance$`search_elapsed_time_s`, "EXPECTED_RESULT")
})

test_that("field_party_chief_name", {
  # tests for the property `field_party_chief_name` (character)
  # Full name of the field party chief.

  # uncomment below to test the property
  #expect_equal(model.instance$`field_party_chief_name`, "EXPECTED_RESULT")
})

test_that("search_result_type_name", {
  # tests for the property `search_result_type_name` (character)
  # Description name of the search result type.

  # uncomment below to test the property
  #expect_equal(model.instance$`search_result_type_name`, "EXPECTED_RESULT")
})

test_that("search_vessel_track_geom", {
  # tests for the property `search_vessel_track_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`search_vessel_track_geom`, "EXPECTED_RESULT")
})

test_that("bottom_trawl_operation_key", {
  # tests for the property `bottom_trawl_operation_key` (character)
  # A 12-character numeric unique identifier for a West Coast Groundfish Bottom Trawl sampling operation.     It is constructed by concatenating key operational attributes into a single string. For example, the operation key **&#x60;202203020001&#x60;** breaks down as follows:    * **Survey Year (Digits 1-4):** The 4-digit year (YYYY) of sampling (e.g., &#x60;2022&#x60;).  * **Operation Type (Digits 5-6):** The 2-digit code representing the survey operation type (e.g., &#x60;03&#x60;).  * **Vessel ID (Digits 7-9):** The 3-digit, zero-padded identifier for the participating vessel (e.g., &#x60;020&#x60;).  * **Operation Increment (Digits 10-12):** The 3-digit, zero-padded sequential operation increment (e.g., &#x60;001&#x60;).

  # uncomment below to test the property
  #expect_equal(model.instance$`bottom_trawl_operation_key`, "EXPECTED_RESULT")
})

test_that("target_station_boundary_geom", {
  # tests for the property `target_station_boundary_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`target_station_boundary_geom`, "EXPECTED_RESULT")
})

test_that("target_station_centroid_geom", {
  # tests for the property `target_station_centroid_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`target_station_centroid_geom`, "EXPECTED_RESULT")
})

test_that("untrawlable_site_reason_name", {
  # tests for the property `untrawlable_site_reason_name` (character)
  # Description of the untrawlable reason.

  # uncomment below to test the property
  #expect_equal(model.instance$`untrawlable_site_reason_name`, "EXPECTED_RESULT")
})
