# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BottomTrawlSpecimens")

model_instance <- BottomTrawlSpecimens$new()

test_that("leg_number", {
  # tests for the property `leg_number` (integer)
  # Leg increment number when a sampling operation took place.  Each vessel participating in the survey partakes in multiple legs (leg #1, #2...) as part of the survey schedule within a given pass, with each survey containing multiple passes per year.  A vessel on the WCGBTS Shelf/Slope Survey typically is scheduled for 5 legs per year, although this is subject to change due to year-to-year schedule differences.

  # uncomment below to test the property
  #expect_equal(model.instance$`leg_number`, "EXPECTED_RESULT")
})

test_that("pass_number", {
  # tests for the property `pass_number` (integer)
  # Pass increment number when a sampling operation took place (i.e. pass #1, #2...).  Each annual survey typically has multiple passes, with each pass being assigned one or several vessels to participate in sampling.

  # uncomment below to test the property
  #expect_equal(model.instance$`pass_number`, "EXPECTED_RESULT")
})

test_that("survey_year", {
  # tests for the property `survey_year` (integer)
  # Calendar year in integer format YYYY during which data was collected.

  # uncomment below to test the property
  #expect_equal(model.instance$`survey_year`, "EXPECTED_RESULT")
})

test_that("vessel_name", {
  # tests for the property `vessel_name` (character)
  # Full name of the commercial or research vessel used to collect the data at sea.

  # uncomment below to test the property
  #expect_equal(model.instance$`vessel_name`, "EXPECTED_RESULT")
})

test_that("sampling_date", {
  # tests for the property `sampling_date` (character)
  # Date when sampling took place, in YYYY-MM-DD ISO8601 format

  # uncomment below to test the property
  #expect_equal(model.instance$`sampling_date`, "EXPECTED_RESULT")
})

test_that("ageing_lab_name", {
  # tests for the property `ageing_lab_name` (character)
  # Name of the ageing lab where this specimen&#39;s age structure was analyzed and aged.

  # uncomment below to test the property
  #expect_equal(model.instance$`ageing_lab_name`, "EXPECTED_RESULT")
})

test_that("data_status_name", {
  # tests for the property `data_status_name` (character)
  # Name of the data point&#39;s current status with respect to its finalization/QC status.  Typically new data submitted directly from the field is flagged as \&quot;Under Review\&quot;,   until it is reviewed, where it is then marked as \&quot;Finalized\&quot;.  Unfinalized data may  be used for any purpose, but for fisheries stock assessment, using/filtering for  finalized data is best.

  # uncomment below to test the property
  #expect_equal(model.instance$`data_status_name`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_at", {
  # tests for the property `net_on_bottom_at` (character)
  # Date and time when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_at`, "EXPECTED_RESULT")
})

test_that("source_wcgbts_id", {
  # tests for the property `source_wcgbts_id` (character)
  # Source specimen identifier from WCGBTS database. UUID version 7 (UUIDv7) is a time-ordered, 128-bit universally unique identifier designed to improve database performance, combining a Unix timestamp (milliseconds precision) with random data. Defined in RFC 9562, it features 48 bits for the timestamp, 74 bits for randomness/entropy, and 6 bits for version/variant. It enables ordered, index-friendly primary keys.

  # uncomment below to test the property
  #expect_equal(model.instance$`source_wcgbts_id`, "EXPECTED_RESULT")
})

test_that("specimen_size_cm", {
  # tests for the property `specimen_size_cm` (numeric)
  # Length or width in cm

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_size_cm`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_at", {
  # tests for the property `net_off_bottom_at` (character)
  # Date and time when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_at`, "EXPECTED_RESULT")
})

test_that("nmfs_project_name", {
  # tests for the property `nmfs_project_name` (character)
  # Name of the project/survey under the National Marine Fisheries Service (NMFS) for which the data was collected.

  # uncomment below to test the property
  #expect_equal(model.instance$`nmfs_project_name`, "EXPECTED_RESULT")
})

test_that("specimen_sex_code", {
  # tests for the property `specimen_sex_code` (character)
  # Sex code

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_sex_code`, "EXPECTED_RESULT")
})

test_that("specimen_age_years", {
  # tests for the property `specimen_age_years` (numeric)
  # Age of the specimen determined by the ageling laboratory using the age structure collected from the specimen after capture.

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_age_years`, "EXPECTED_RESULT")
})

test_that("specimen_weight_kg", {
  # tests for the property `specimen_weight_kg` (numeric)
  # Recorded weight of the specimen in kilograms.

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_weight_kg`, "EXPECTED_RESULT")
})

test_that("actual_station_code", {
  # tests for the property `actual_station_code` (character)
  # Unique identifier for the sampling site visited. For the West Coast Groundfish Bottom Trawl Shelf/Slope Survey, sites follow a gridded pattern. Site codes incrementing sequentially by one from North to South and West to East, with the site furthest to the North starting at 4039 and the site furthest to the south ending at 23399. Most site codes are integers, but present as text data types to accommodate historical formats which included alphanumeric values. Historical site splits are represented by floating point numbers (site 44444 split to 44444.1 and 44444.2). The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_code`, "EXPECTED_RESULT")
})

test_that("age_last_analyzed_at", {
  # tests for the property `age_last_analyzed_at` (character)
  # Date the last time this specimen age structure was aged by the ageing lab

  # uncomment below to test the property
  #expect_equal(model.instance$`age_last_analyzed_at`, "EXPECTED_RESULT")
})

test_that("age_sample_type_name", {
  # tests for the property `age_sample_type_name` (character)
  # Type of age sample

  # uncomment below to test the property
  #expect_equal(model.instance$`age_sample_type_name`, "EXPECTED_RESULT")
})

test_that("best_tow_latitude_dd", {
  # tests for the property `best_tow_latitude_dd` (numeric)
  # Summarized location of the tow representing the single point in space that best represents where the tow sampling took place. Typically this location is derived by combining the median latitude and longitude of the estimated gear track wihle the gear is fishing and in contact with the bottom. Latitude presented as decimal degrees with up to eight points of precision. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_latitude_dd`, "EXPECTED_RESULT")
})

test_that("tow_performance_name", {
  # tests for the property `tow_performance_name` (character)
  # Tows should be marked as \&quot;satisfactory\&quot; or \&quot;unsatisfactory\&quot;, with satisfactory tows typically considered viable for stock assessment.

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_performance_name`, "EXPECTED_RESULT")
})

test_that("best_tow_longitude_dd", {
  # tests for the property `best_tow_longitude_dd` (numeric)
  # Summarized location of the tow representing the single point in space that best represents where the tow sampling took place. Typically this location is derived by combining the median latitude and longitude of the estimated gear track wihle the gear is fishing and in contact with the bottom. Longitude presented as decimal degrees with up to eight points of precision. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_longitude_dd`, "EXPECTED_RESULT")
})

test_that("best_tow_location_geom", {
  # tests for the property `best_tow_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_location_geom`, "EXPECTED_RESULT")
})

test_that("ovary_last_analyzed_at", {
  # tests for the property `ovary_last_analyzed_at` (character)
  # Date the last time this specimen ovary structure was aged by the maturities lab

  # uncomment below to test the property
  #expect_equal(model.instance$`ovary_last_analyzed_at`, "EXPECTED_RESULT")
})

test_that("ovary_proportion_atresia", {
  # tests for the property `ovary_proportion_atresia` (numeric)
  # The post-season measured proportion of oocytes (eggs) in the ovary sample that are undergoing atresia—the biological process of breaking down and reabsorbing unspawned eggs. A higher proportion typically indicates environmental stress, skipped spawning, or the end of a reproductive cycle as the fish recycles energy.

  # uncomment below to test the property
  #expect_equal(model.instance$`ovary_proportion_atresia`, "EXPECTED_RESULT")
})

test_that("specimen_life_stage_name", {
  # tests for the property `specimen_life_stage_name` (character)
  # Life stage or ontogeny designation of the catch sample (i.e. egg case, larval, adult, YoY).  If not specified (it typically is not called out by scientists in the field) the catch can be assumed to be fully mature adults.

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_life_stage_name`, "EXPECTED_RESULT")
})

test_that("data_readiness_level_code", {
  # tests for the property `data_readiness_level_code` (character)
  # The code representing the data readiness level.     Values include:  * &#x60;L0&#x60;  * &#x60;L1&#x60;  * &#x60;L2&#x60;  * &#x60;L3&#x60;  * &#x60;L4&#x60;

  # uncomment below to test the property
  #expect_equal(model.instance$`data_readiness_level_code`, "EXPECTED_RESULT")
})

test_that("specimen_age_sample_label", {
  # tests for the property `specimen_age_sample_label` (character)
  # Label for age sample

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_age_sample_label`, "EXPECTED_RESULT")
})

test_that("bottom_trawl_operation_key", {
  # tests for the property `bottom_trawl_operation_key` (character)
  # 12-character numeric unique identifier for a West Coast Groundfish Bottom Trawl sampling operation. Digits 1-4 represent the year (YYYY) of sampling, digits 5-6 represent the survey operation type, digits 7-9 represent the zero-padded vessel identifier, digits 10-12 represent the zero-padded sequential operation increment.

  # uncomment below to test the property
  #expect_equal(model.instance$`bottom_trawl_operation_key`, "EXPECTED_RESULT")
})

test_that("actual_station_centroid_key", {
  # tests for the property `actual_station_centroid_key` (integer)
  # A composite spatial key that uniquely identifies the centroid of a WCGBTS (West Coast Groundfish Bottom Trawl Survey) sampling station grid cell.     This key is a fixed 8-character string constructed by converting decimal degree coordinates into Degrees and Decimal Minutes (DDM), stripping away negative signs and truncating specific digits to create a consistent spatial identifier.    ### Component Breakdown  The 8-character format strictly follows the pattern **&#x60;[Lat Degrees][Lat Minutes][Lon Degrees][Lon Minutes]&#x60;**:    * **Latitude Degrees (2 characters):** The whole number of the decimal latitude (e.g., &#x60;43.58&#x60; becomes &#x60;43&#x60;).  * **Latitude Minutes (2 characters):** The decimal remainder of the latitude multiplied by 60 and rounded to the nearest whole number (e.g., &#x60;0.58139 * 60 &#x3D; 34.88&#x60;, which rounds to &#x60;35&#x60;).  * **Longitude Degrees (2 characters):** The whole number of the longitude, ignoring the negative sign (West) and dropping the leading hundreds place (e.g., &#x60;-124.61&#x60; becomes &#x60;24&#x60;).  * **Longitude Minutes (2 characters):** The decimal remainder of the longitude multiplied by 60 and rounded to the nearest whole number (e.g., &#x60;0.61465 * 60 &#x3D; 36.87&#x60;, which rounds to &#x60;37&#x60;).    &gt; **Example:** A grid cell centroid located at decimal coordinates **&#x60;43.58139678, -124.61465068&#x60;** results in the centroid key **&#x60;43352437&#x60;**.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_centroid_key`, "EXPECTED_RESULT")
})

test_that("actual_station_history_json", {
  # tests for the property `actual_station_history_json` (object)
  # JSON listing array of historical activation/deactivations of the actual station sampled. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_history_json`, "EXPECTED_RESULT")
})

test_that("specimen_ovary_sample_label", {
  # tests for the property `specimen_ovary_sample_label` (character)
  # Label for ovary sample

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_ovary_sample_label`, "EXPECTED_RESULT")
})

test_that("specimen_tissue_sample_label", {
  # tests for the property `specimen_tissue_sample_label` (character)
  # Label for tissue sample

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_tissue_sample_label`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_category", {
  # tests for the property `best_available_taxon_category` (character)
  # Broad scientific category of the taxon (e.g., Fish, Invertebrate, Mammal, Marine Plant). \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_category`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_is_coral", {
  # tests for the property `best_available_taxon_is_coral` (character)
  # Boolean flag indicating if the taxon belongs to the subclass Octocorallia (corals). \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_is_coral`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_itis_tsn", {
  # tests for the property `best_available_taxon_itis_tsn` (integer)
  # Taxonomic Serial Number (TSN) is a unique, stable, and persistent numeric identifier assigned by the Integrated Taxonomic Information System (ITIS) to scientific names of organisms. It serves as a non-intelligent, permanent key for tracking species, synonyms, and taxonomic changes across various databases, ensuring standardized classification of flora and fauna. \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_itis_tsn`, "EXPECTED_RESULT")
})

test_that("specimen_finclip_sample_label", {
  # tests for the property `specimen_finclip_sample_label` (character)
  # Label for finclip sample

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_finclip_sample_label`, "EXPECTED_RESULT")
})

test_that("specimen_stomach_sample_label", {
  # tests for the property `specimen_stomach_sample_label` (character)
  # Label for stomach sample

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_stomach_sample_label`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_is_sponge", {
  # tests for the property `best_available_taxon_is_sponge` (character)
  # Boolean flag indicating if the taxon belongs to the phylum Porifera (sponges). \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_is_sponge`, "EXPECTED_RESULT")
})

test_that("specimen_size_sample_type_name", {
  # tests for the property `specimen_size_sample_type_name` (character)
  # Type of length/width measurement taken sample

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_size_sample_type_name`, "EXPECTED_RESULT")
})

test_that("actual_station_deactivation_year", {
  # tests for the property `actual_station_deactivation_year` (integer)
  # The year YYYY when the actual station sampled was last deactivated, if the site is currently inactive. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_deactivation_year`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_common_name", {
  # tests for the property `best_available_taxon_common_name` (character)
  # Common name of the species preferred by the Northwest Fisheries Science Center. \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_common_name`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_is_rockfish", {
  # tests for the property `best_available_taxon_is_rockfish` (character)
  # Boolean flag indicating if the taxon belongs to the genus Sebastes (rockfishes). \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_is_rockfish`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_subcategory", {
  # tests for the property `best_available_taxon_subcategory` (character)
  # More granular scientific subcategory of the taxon (e.g., Rockfish, Flatfish, Roundfish, Crab, Shrimp). \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_subcategory`, "EXPECTED_RESULT")
})

test_that("lab_analyzed_maturity_stage_name", {
  # tests for the property `lab_analyzed_maturity_stage_name` (character)
  # Maturity designation and certainty of the designation summary.

  # uncomment below to test the property
  #expect_equal(model.instance$`lab_analyzed_maturity_stage_name`, "EXPECTED_RESULT")
})

test_that("actual_station_depth_stratum_name", {
  # tests for the property `actual_station_depth_stratum_name` (character)
  # Name of the depth stratum that the sampling site falls into. Sampling on the West Coast Groundfish Bottom Trawl Shelf/Slope Survey follows a randomly stratified design, with sampling sites falling into one of three depth strata: 30-100 fathoms, 100-300 fathoms, and 300-700 fathoms. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_depth_stratum_name`, "EXPECTED_RESULT")
})

test_that("data_readiness_level_display_name", {
  # tests for the property `data_readiness_level_display_name` (character)
  # The formatted display name combining the readiness level code and its status.     Values include:  * &#x60;L0 - RAW&#x60;  * &#x60;L1 - PRELIMINARY&#x60;  * &#x60;L2 - VERIFIED&#x60;  * &#x60;L3 - HARMONIZED&#x60;  * &#x60;L4 - DERIVED&#x60;

  # uncomment below to test the property
  #expect_equal(model.instance$`data_readiness_level_display_name`, "EXPECTED_RESULT")
})

test_that("is_actual_station_currently_active", {
  # tests for the property `is_actual_station_currently_active` (character)
  # Boolean indicating if the actual station sampled is currently active. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`is_actual_station_currently_active`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_worms_aphia_id", {
  # tests for the property `best_available_taxon_worms_aphia_id` (integer)
  # The AphiaID is a unique, stable, and persistent numerical identifier used within the World Register of Marine Species (WoRMS) database to identify, track, and manage marine organisms, including their taxonomic classification, synonyms, and related biological traits. It serves as the core taxonomic infrastructure, ensuring data consistency and enabling integration with external biological databases. \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_worms_aphia_id`, "EXPECTED_RESULT")
})

test_that("actual_station_latitude_stratum_name", {
  # tests for the property `actual_station_latitude_stratum_name` (character)
  # Name of the latitude stratum that the sampling site falls into. Sampling on the West Coast Groundfish Bottom Trawl Shelf/Slope Survey follows a randomly stratified design, with sampling sites falling into one of two latitude strata: North of Point Conception (&gt;34°30&#39;N) or South of Point Conception (&lt;34°30&#39;N). The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_latitude_stratum_name`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_is_invertebrate", {
  # tests for the property `best_available_taxon_is_invertebrate` (character)
  # Boolean flag indicating if the taxon is an invertebrate (Kingdom Animalia, excluding Subphylum Vertebrata). \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_is_invertebrate`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_scientific_name", {
  # tests for the property `best_available_taxon_scientific_name` (character)
  # Scientific name or latinized nomenclature of the species caught used to uniquely identify taxonomic classification. \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_scientific_name`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_is_pacific_salmon", {
  # tests for the property `best_available_taxon_is_pacific_salmon` (character)
  # Boolean flag indicating if the taxon belongs to the genus Oncorhynchus (Pacific salmon). \&quot;Best available\&quot; designation reflects the taxonomic classification of the species after postseason review, which may be the same or different than the taxonomic classification determined in the field at time of collection.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_is_pacific_salmon`, "EXPECTED_RESULT")
})

test_that("was_actual_station_active_when_sampled", {
  # tests for the property `was_actual_station_active_when_sampled` (character)
  # Boolean indicating if the actual station was active at the time it was sampled. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`was_actual_station_active_when_sampled`, "EXPECTED_RESULT")
})

test_that("was_target_station_active_when_sampled", {
  # tests for the property `was_target_station_active_when_sampled` (character)
  # Boolean indicating if the target station was active at the time of sampling. The \&quot;target\&quot; sampling site designation indicates that the site was the target for sampling for the particular operation. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to the \&quot;best\&quot; preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`was_target_station_active_when_sampled`, "EXPECTED_RESULT")
})

test_that("actual_station_current_deactivation_reasons", {
  # tests for the property `actual_station_current_deactivation_reasons` (character)
  # Comma-separated list of current reasons that a station is listed as inactive.  Value should be null unless the station is currently inactive.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_current_deactivation_reasons`, "EXPECTED_RESULT")
})
