# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NwfscTriennialSpecimenLengths")

model_instance <- NwfscTriennialSpecimenLengths$new()

test_that("survey_year", {
  # tests for the property `survey_year` (integer)
  # Calendar year in integer format YYYY during which data was collected.

  # uncomment below to test the property
  #expect_equal(model.instance$`survey_year`, "EXPECTED_RESULT")
})

test_that("vessel_name", {
  # tests for the property `vessel_name` (character)
  # Full capitalized name of the commercial or research vessel used to collect the data at sea.  As a general rule, names do not include the preceiding ship   or vessel prefix (i.e. Last Straw, NOT F/V Last Straw).

  # uncomment below to test the property
  #expect_equal(model.instance$`vessel_name`, "EXPECTED_RESULT")
})

test_that("sampling_date", {
  # tests for the property `sampling_date` (character)
  # Date that the individual was sampled in the field.

  # uncomment below to test the property
  #expect_equal(model.instance$`sampling_date`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_at", {
  # tests for the property `net_on_bottom_at` (character)
  # when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_at`, "EXPECTED_RESULT")
})

test_that("specimen_size_cm", {
  # tests for the property `specimen_size_cm` (numeric)
  # The total length/width/dimension of the sampled fish/specimen, measured in centimeters.

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_size_cm`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_at", {
  # tests for the property `net_off_bottom_at` (character)
  # when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_at`, "EXPECTED_RESULT")
})

test_that("nmfs_project_name", {
  # tests for the property `nmfs_project_name` (character)
  # Name of the project/survey under the National Marine Fisheries Service (NMFS) for which the data was collected.

  # uncomment below to test the property
  #expect_equal(model.instance$`nmfs_project_name`, "EXPECTED_RESULT")
})

test_that("specimen_sex_code", {
  # tests for the property `specimen_sex_code` (character)
  # Abbreviated code for the specimen&#39;s sex (e.g., M, F, U).

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_sex_code`, "EXPECTED_RESULT")
})

test_that("specimen_sex_name", {
  # tests for the property `specimen_sex_name` (character)
  # Full descriptive name for the specimen&#39;s sex.

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_sex_name`, "EXPECTED_RESULT")
})

test_that("actual_station_code", {
  # tests for the property `actual_station_code` (character)
  # Unique identifier for the sampling site visited. For the West Coast Groundfish Bottom Trawl Shelf/Slope Survey, sites follow a gridded pattern. Site codes incrementing sequentially by one from North to South and West to East, with the site furthest to the North starting at 4039 and the site furthest to the south ending at 23399. Most site codes are integers, but present as text data types to accommodate historical formats which included alphanumeric values. Historical site splits are represented by floating point numbers (site 44444 split to 44444.1 and 44444.2). The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_code`, "EXPECTED_RESULT")
})

test_that("best_tow_latitude_dd", {
  # tests for the property `best_tow_latitude_dd` (character)
  # Latitude of the single point in space that best represents where the tow sampling took place. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_latitude_dd`, "EXPECTED_RESULT")
})

test_that("tow_performance_name", {
  # tests for the property `tow_performance_name` (character)
  # Descriptive name of the tow performance status.

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_performance_name`, "EXPECTED_RESULT")
})

test_that("best_tow_longitude_dd", {
  # tests for the property `best_tow_longitude_dd` (character)
  # Longitude of the single point in space that best represents where the tow sampling took place. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_longitude_dd`, "EXPECTED_RESULT")
})

test_that("best_tow_location_geom", {
  # tests for the property `best_tow_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_location_geom`, "EXPECTED_RESULT")
})

test_that("specimen_size_type_name", {
  # tests for the property `specimen_size_type_name` (character)
  # Descriptive name of the associated specimen size (e.g. lenght/width)

  # uncomment below to test the property
  #expect_equal(model.instance$`specimen_size_type_name`, "EXPECTED_RESULT")
})

test_that("bottom_trawl_operation_key", {
  # tests for the property `bottom_trawl_operation_key` (character)
  # A 12-character numeric unique identifier for a West Coast Groundfish Bottom Trawl sampling operation.     It is constructed by concatenating key operational attributes into a single string. For example, the operation key **&#x60;202203020001&#x60;** breaks down as follows:    * **Survey Year (Digits 1-4):** The 4-digit year (YYYY) of sampling (e.g., &#x60;2022&#x60;).  * **Operation Type (Digits 5-6):** The 2-digit code representing the survey operation type (e.g., &#x60;03&#x60;).  * **Vessel ID (Digits 7-9):** The 3-digit, zero-padded identifier for the participating vessel (e.g., &#x60;020&#x60;).  * **Operation Increment (Digits 10-12):** The 3-digit, zero-padded sequential operation increment (e.g., &#x60;001&#x60;).

  # uncomment below to test the property
  #expect_equal(model.instance$`bottom_trawl_operation_key`, "EXPECTED_RESULT")
})

test_that("on_bottom_seafloor_depth_m", {
  # tests for the property `on_bottom_seafloor_depth_m` (numeric)
  # the depth of the seafloor to sea surface surface in meters.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_seafloor_depth_m`, "EXPECTED_RESULT")
})

test_that("actual_station_centroid_key", {
  # tests for the property `actual_station_centroid_key` (integer)
  # A composite spatial key that uniquely identifies the centroid of a WCGBTS (West Coast Groundfish Bottom Trawl Survey) sampling station grid cell.     This key is a fixed 8-character string constructed by converting decimal degree coordinates into Degrees and Decimal Minutes (DDM), stripping away negative signs and truncating specific digits to create a consistent spatial identifier.    ### Component Breakdown  The 8-character format strictly follows the pattern **&#x60;[Lat Degrees][Lat Minutes][Lon Degrees][Lon Minutes]&#x60;**:    * **Latitude Degrees (2 characters):** The whole number of the decimal latitude (e.g., &#x60;43.58&#x60; becomes &#x60;43&#x60;).  * **Latitude Minutes (2 characters):** The decimal remainder of the latitude multiplied by 60 and rounded to the nearest whole number (e.g., &#x60;0.58139 * 60 &#x3D; 34.88&#x60;, which rounds to &#x60;35&#x60;).  * **Longitude Degrees (2 characters):** The whole number of the longitude, ignoring the negative sign (West) and dropping the leading hundreds place (e.g., &#x60;-124.61&#x60; becomes &#x60;24&#x60;).  * **Longitude Minutes (2 characters):** The decimal remainder of the longitude multiplied by 60 and rounded to the nearest whole number (e.g., &#x60;0.61465 * 60 &#x3D; 36.87&#x60;, which rounds to &#x60;37&#x60;).    &gt; **Example:** A grid cell centroid located at decimal coordinates **&#x60;43.58139678, -124.61465068&#x60;** results in the centroid key **&#x60;43352437&#x60;**.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_centroid_key`, "EXPECTED_RESULT")
})

test_that("actual_station_history_json", {
  # tests for the property `actual_station_history_json` (object)
  # JSON listing array of historical activation/deactivations of the actual station sampled. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_history_json`, "EXPECTED_RESULT")
})

test_that("actual_station_deactivation_year", {
  # tests for the property `actual_station_deactivation_year` (integer)
  # The year YYYY when the actual station sampled was last deactivated, if the site is currently inactive. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_deactivation_year`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_common_name", {
  # tests for the property `best_available_taxon_common_name` (character)
  # Field identified scientific name for the sampled taxon.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_common_name`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_vessel_latitude_dd", {
  # tests for the property `net_on_bottom_vessel_latitude_dd` (character)
  # Latitude of the vessel when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("actual_station_depth_stratum_name", {
  # tests for the property `actual_station_depth_stratum_name` (character)
  # Name of the depth stratum that the sampling site falls into. Sampling on the West Coast Groundfish Bottom Trawl Shelf/Slope Survey follows a randomly stratified design, with sampling sites falling into one of three depth strata: 30-100 fathoms, 100-300 fathoms, and 300-700 fathoms. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_depth_stratum_name`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_vessel_latitude_dd", {
  # tests for the property `net_off_bottom_vessel_latitude_dd` (character)
  # Latitude of the vessel when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_vessel_longitude_dd", {
  # tests for the property `net_on_bottom_vessel_longitude_dd` (character)
  # Longitude of the vessel when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("is_actual_station_currently_active", {
  # tests for the property `is_actual_station_currently_active` (character)
  # Boolean indicating if the actual station sampled is currently active. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`is_actual_station_currently_active`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_vessel_longitude_dd", {
  # tests for the property `net_off_bottom_vessel_longitude_dd` (character)
  # Longitude of the vessel when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_vessel_location_geom", {
  # tests for the property `net_on_bottom_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_vessel_location_geom", {
  # tests for the property `net_off_bottom_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("actual_station_latitude_stratum_name", {
  # tests for the property `actual_station_latitude_stratum_name` (character)
  # Name of the latitude stratum that the sampling site falls into. Sampling on the West Coast Groundfish Bottom Trawl Shelf/Slope Survey follows a randomly stratified design, with sampling sites falling into one of two latitude strata: North of Point Conception (&gt;34°30&#39;N) or South of Point Conception (&lt;34°30&#39;N). The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_latitude_stratum_name`, "EXPECTED_RESULT")
})

test_that("best_available_taxon_scientific_name", {
  # tests for the property `best_available_taxon_scientific_name` (character)
  # Best available scientific name for the sampled taxon.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_available_taxon_scientific_name`, "EXPECTED_RESULT")
})

test_that("was_actual_station_active_when_sampled", {
  # tests for the property `was_actual_station_active_when_sampled` (character)
  # Boolean indicating if the actual station was active at the time it was sampled. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`was_actual_station_active_when_sampled`, "EXPECTED_RESULT")
})

test_that("was_target_station_active_when_sampled", {
  # tests for the property `was_target_station_active_when_sampled` (character)
  # Boolean indicating if the target station was active at the time of sampling. The \&quot;target\&quot; sampling site designation indicates that the site was the target for sampling for the particular operation. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to the \&quot;best\&quot; preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`was_target_station_active_when_sampled`, "EXPECTED_RESULT")
})

test_that("best_tow_location_calculation_method_id", {
  # tests for the property `best_tow_location_calculation_method_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_location_calculation_method_id`, "EXPECTED_RESULT")
})

test_that("bottom_trawl_triennial_specimen_length_id", {
  # tests for the property `bottom_trawl_triennial_specimen_length_id` (character)
  # Surrogate unique key for each triennial specimen length record.

  # uncomment below to test the property
  #expect_equal(model.instance$`bottom_trawl_triennial_specimen_length_id`, "EXPECTED_RESULT")
})

test_that("actual_station_current_deactivation_reasons", {
  # tests for the property `actual_station_current_deactivation_reasons` (character)
  # Comma-separated list of current reasons that a station is listed as inactive.  Value should be null unless the station is currently inactive.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_current_deactivation_reasons`, "EXPECTED_RESULT")
})
