# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NwfscSurveyTaxonomy")

model_instance <- NwfscSurveyTaxonomy$new()

test_that("is_bird", {
  # tests for the property `is_bird` (character)
  # Flag indicating if taxon is a bird

  # uncomment below to test the property
  #expect_equal(model.instance$`is_bird`, "EXPECTED_RESULT")
})

test_that("is_coral", {
  # tests for the property `is_coral` (character)
  # Flag indicating if taxon is a coral

  # uncomment below to test the property
  #expect_equal(model.instance$`is_coral`, "EXPECTED_RESULT")
})

test_that("is_skate", {
  # tests for the property `is_skate` (character)
  # Flag indicating if taxon is a skate

  # uncomment below to test the property
  #expect_equal(model.instance$`is_skate`, "EXPECTED_RESULT")
})

test_that("is_smelt", {
  # tests for the property `is_smelt` (character)
  # Flag indicating if taxon is a smelt

  # uncomment below to test the property
  #expect_equal(model.instance$`is_smelt`, "EXPECTED_RESULT")
})

test_that("is_squid", {
  # tests for the property `is_squid` (character)
  # Flag indicating if taxon is a squid

  # uncomment below to test the property
  #expect_equal(model.instance$`is_squid`, "EXPECTED_RESULT")
})

test_that("itis_tsn", {
  # tests for the property `itis_tsn` (integer)
  # ITIS Taxonomic Serial Number

  # uncomment below to test the property
  #expect_equal(model.instance$`itis_tsn`, "EXPECTED_RESULT")
})

test_that("is_mammal", {
  # tests for the property `is_mammal` (character)
  # Flag indicating if taxon is a mammal

  # uncomment below to test the property
  #expect_equal(model.instance$`is_mammal`, "EXPECTED_RESULT")
})

test_that("is_sponge", {
  # tests for the property `is_sponge` (character)
  # Flag indicating if taxon is a sponge

  # uncomment below to test the property
  #expect_equal(model.instance$`is_sponge`, "EXPECTED_RESULT")
})

test_that("is_herring", {
  # tests for the property `is_herring` (character)
  # Flag indicating if taxon is a herring

  # uncomment below to test the property
  #expect_equal(model.instance$`is_herring`, "EXPECTED_RESULT")
})

test_that("is_reptile", {
  # tests for the property `is_reptile` (character)
  # Flag indicating if taxon is a reptile

  # uncomment below to test the property
  #expect_equal(model.instance$`is_reptile`, "EXPECTED_RESULT")
})

test_that("is_rockfish", {
  # tests for the property `is_rockfish` (character)
  # Flag indicating if taxon is a rockfish

  # uncomment below to test the property
  #expect_equal(model.instance$`is_rockfish`, "EXPECTED_RESULT")
})

test_that("is_bony_fish", {
  # tests for the property `is_bony_fish` (character)
  # Flag indicating if taxon is a bony fish

  # uncomment below to test the property
  #expect_equal(model.instance$`is_bony_fish`, "EXPECTED_RESULT")
})

test_that("itis_lineage", {
  # tests for the property `itis_lineage` (object)
  # An ordered array of JSON documents representing each level of the ITIS taxonomic lineage, where the final entry contains ITIS TSN and URL mappings.

  # uncomment below to test the property
  #expect_equal(model.instance$`itis_lineage`, "EXPECTED_RESULT")
})

test_that("itis_website", {
  # tests for the property `itis_website` (character)
  # Link to ITIS website

  # uncomment below to test the property
  #expect_equal(model.instance$`itis_website`, "EXPECTED_RESULT")
})

test_that("is_vertebrate", {
  # tests for the property `is_vertebrate` (character)
  # Flag indicating if taxon is a vertebrate

  # uncomment below to test the property
  #expect_equal(model.instance$`is_vertebrate`, "EXPECTED_RESULT")
})

test_that("nwfsc_lineage", {
  # tests for the property `nwfsc_lineage` (object)
  # An ordered array of JSON documents representing each level of the NWFSC taxonomic lineage, where the final entry in the array corresponds to the current taxon and contains authority website linkages and IDs.

  # uncomment below to test the property
  #expect_equal(model.instance$`nwfsc_lineage`, "EXPECTED_RESULT")
})

test_that("taxon_aliases", {
  # tests for the property `taxon_aliases` (character)
  # Array of aliases for the taxon

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_aliases`, "EXPECTED_RESULT")
})

test_that("worms_lineage", {
  # tests for the property `worms_lineage` (object)
  # An ordered array of JSON documents representing each level of the WoRMS taxonomic lineage, where the final entry contains WoRMS Aphia ID and URL mappings.

  # uncomment below to test the property
  #expect_equal(model.instance$`worms_lineage`, "EXPECTED_RESULT")
})

test_that("worms_website", {
  # tests for the property `worms_website` (character)
  # Link to WoRMS website

  # uncomment below to test the property
  #expect_equal(model.instance$`worms_website`, "EXPECTED_RESULT")
})

test_that("taxon_category", {
  # tests for the property `taxon_category` (character)
  # Broad category of the taxon

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_category`, "EXPECTED_RESULT")
})

test_that("worms_aphia_id", {
  # tests for the property `worms_aphia_id` (integer)
  # WoRMS AphiaID

  # uncomment below to test the property
  #expect_equal(model.instance$`worms_aphia_id`, "EXPECTED_RESULT")
})

test_that("is_invertebrate", {
  # tests for the property `is_invertebrate` (character)
  # Flag indicating if taxon is an invertebrate

  # uncomment below to test the property
  #expect_equal(model.instance$`is_invertebrate`, "EXPECTED_RESULT")
})

test_that("is_jawless_fish", {
  # tests for the property `is_jawless_fish` (character)
  # Flag indicating if taxon is a jawless fish

  # uncomment below to test the property
  #expect_equal(model.instance$`is_jawless_fish`, "EXPECTED_RESULT")
})

test_that("itis_api_result", {
  # tests for the property `itis_api_result` (object)
  # Full API result from ITIS

  # uncomment below to test the property
  #expect_equal(model.instance$`itis_api_result`, "EXPECTED_RESULT")
})

test_that("scientific_name", {
  # tests for the property `scientific_name` (character)
  # Scientific name of the taxon

  # uncomment below to test the property
  #expect_equal(model.instance$`scientific_name`, "EXPECTED_RESULT")
})

test_that("worms_api_result", {
  # tests for the property `worms_api_result` (object)
  # Full API result from WoRMS

  # uncomment below to test the property
  #expect_equal(model.instance$`worms_api_result`, "EXPECTED_RESULT")
})

test_that("is_pacific_salmon", {
  # tests for the property `is_pacific_salmon` (character)
  # Flag indicating if taxon is a Pacific salmon

  # uncomment below to test the property
  #expect_equal(model.instance$`is_pacific_salmon`, "EXPECTED_RESULT")
})

test_that("taxon_subcategory", {
  # tests for the property `taxon_subcategory` (character)
  # Subcategory of the taxon

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_subcategory`, "EXPECTED_RESULT")
})

test_that("hierarchy_level_name", {
  # tests for the property `hierarchy_level_name` (character)
  # Taxonomic rank (e.g. Species, Genus)

  # uncomment below to test the property
  #expect_equal(model.instance$`hierarchy_level_name`, "EXPECTED_RESULT")
})

test_that("taxon_change_history", {
  # tests for the property `taxon_change_history` (object)
  # Aggregated historical records of taxonomic changes tracked over time as a Slowly Changing Dimension (SCD Type 2).

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_change_history`, "EXPECTED_RESULT")
})

test_that("is_nonspecific_organic", {
  # tests for the property `is_nonspecific_organic` (character)
  # Flag indicating if taxon is nonspecific organic

  # uncomment below to test the property
  #expect_equal(model.instance$`is_nonspecific_organic`, "EXPECTED_RESULT")
})

test_that("parent_scientific_name", {
  # tests for the property `parent_scientific_name` (character)
  # Scientific name of the parent taxon

  # uncomment below to test the property
  #expect_equal(model.instance$`parent_scientific_name`, "EXPECTED_RESULT")
})

test_that("bottom_trawl_taxon_alias", {
  # tests for the property `bottom_trawl_taxon_alias` (character)
  # Bottom Trawl preferred alias

  # uncomment below to test the property
  #expect_equal(model.instance$`bottom_trawl_taxon_alias`, "EXPECTED_RESULT")
})

test_that("hook_and_line_taxon_alias", {
  # tests for the property `hook_and_line_taxon_alias` (character)
  # Hook &amp; Line preferred alias

  # uncomment below to test the property
  #expect_equal(model.instance$`hook_and_line_taxon_alias`, "EXPECTED_RESULT")
})

test_that("legacy_warehouse_source_taxon_key", {
  # tests for the property `legacy_warehouse_source_taxon_key` (character)
  # Source key for legacy warehouse

  # uncomment below to test the property
  #expect_equal(model.instance$`legacy_warehouse_source_taxon_key`, "EXPECTED_RESULT")
})
