# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NwfscAllTaxonCategories")

model_instance <- NwfscAllTaxonCategories$new()

test_that("label", {
  # tests for the property `label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})
