# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BottomTrawlTows")

model_instance <- BottomTrawlTows$new()

test_that("leg_number", {
  # tests for the property `leg_number` (integer)
  # Leg increment number when a sampling operation took place. Each vessel participating in the survey partakes in multiple legs (leg #1, #2...) as part of the survey schedule within a given pass, with each survey containing multiple passes per year. A vessel on the WCGBTS Shelf/Slope Survey typically is scheduled for 5 legs per year, although this is subject to change due to year-to-year schedule differences.

  # uncomment below to test the property
  #expect_equal(model.instance$`leg_number`, "EXPECTED_RESULT")
})

test_that("doors_up_at", {
  # tests for the property `doors_up_at` (character)
  # when the trawl doors are first visible at the sea surface from the deck/wheelhouse. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_up_at`, "EXPECTED_RESULT")
})

test_that("pass_number", {
  # tests for the property `pass_number` (integer)
  # Pass increment number when a sampling operation took place (i.e. pass #1, #2...). Each annual survey typically has multiple passes, with each pass being assigned one or several vessels to participate in sampling.

  # uncomment below to test the property
  #expect_equal(model.instance$`pass_number`, "EXPECTED_RESULT")
})

test_that("survey_year", {
  # tests for the property `survey_year` (integer)
  # Calendar year in integer format YYYY during which data was collected.

  # uncomment below to test the property
  #expect_equal(model.instance$`survey_year`, "EXPECTED_RESULT")
})

test_that("vessel_name", {
  # tests for the property `vessel_name` (character)
  # Full capitalized name of the commercial or research vessel used to collect the data at sea.  As a general rule, names do not include the preceiding ship   or vessel prefix (i.e. Last Straw, NOT F/V Last Straw).

  # uncomment below to test the property
  #expect_equal(model.instance$`vessel_name`, "EXPECTED_RESULT")
})

test_that("captain_name", {
  # tests for the property `captain_name` (character)
  # The captain or skipper in charge of operating the vessel during an operation&#39;s sampling.

  # uncomment below to test the property
  #expect_equal(model.instance$`captain_name`, "EXPECTED_RESULT")
})

test_that("doors_out_at", {
  # tests for the property `doors_out_at` (character)
  # when the trawl doors are fully out, wire is fully deployed, and winch is stopped. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_out_at`, "EXPECTED_RESULT")
})

test_that("doors_set_at", {
  # tests for the property `doors_set_at` (character)
  # when the trawl doors were set after gear was deployed. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_set_at`, "EXPECTED_RESULT")
})

test_that("sampling_date", {
  # tests for the property `sampling_date` (character)
  # Date when sampling took place, in YYYY-MM-DD ISO8601 format

  # uncomment below to test the property
  #expect_equal(model.instance$`sampling_date`, "EXPECTED_RESULT")
})

test_that("tow_started_at", {
  # tests for the property `tow_started_at` (character)
  # when the tow was first initiated and gear was deployed. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_started_at`, "EXPECTED_RESULT")
})

test_that("wave_height_ft", {
  # tests for the property `wave_height_ft` (numeric)
  # Height of waves in feet.

  # uncomment below to test the property
  #expect_equal(model.instance$`wave_height_ft`, "EXPECTED_RESULT")
})

test_that("swell_height_ft", {
  # tests for the property `swell_height_ft` (numeric)
  # Height of swell in feet.

  # uncomment below to test the property
  #expect_equal(model.instance$`swell_height_ft`, "EXPECTED_RESULT")
})

test_that("data_status_name", {
  # tests for the property `data_status_name` (character)
  # Name of the data point&#39;s current status with respect to its finalization/QC status.  Typically new data submitted directly from the field is flagged as \&quot;Under Review\&quot;,   until it is reviewed, where it is then marked as \&quot;Finalized\&quot;.  Unfinalized data may  be used for any purpose, but for fisheries stock assessment, using/filtering for  finalized data is best.

  # uncomment below to test the property
  #expect_equal(model.instance$`data_status_name`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_at", {
  # tests for the property `net_on_bottom_at` (character)
  # when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_at`, "EXPECTED_RESULT")
})

test_that("scientist_1_name", {
  # tests for the property `scientist_1_name` (character)
  # The full name of the first scientist/biologist participating in the tow.

  # uncomment below to test the property
  #expect_equal(model.instance$`scientist_1_name`, "EXPECTED_RESULT")
})

test_that("scientist_2_name", {
  # tests for the property `scientist_2_name` (character)
  # The full name of the second scientist/biologist participating in the tow.

  # uncomment below to test the property
  #expect_equal(model.instance$`scientist_2_name`, "EXPECTED_RESULT")
})

test_that("scientist_3_name", {
  # tests for the property `scientist_3_name` (character)
  # The full name of the third scientist/biologist participating in the tow.

  # uncomment below to test the property
  #expect_equal(model.instance$`scientist_3_name`, "EXPECTED_RESULT")
})

test_that("scientist_4_name", {
  # tests for the property `scientist_4_name` (character)
  # The full name of the fourth scientist/biologist participating in the tow.

  # uncomment below to test the property
  #expect_equal(model.instance$`scientist_4_name`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_at", {
  # tests for the property `net_off_bottom_at` (character)
  # when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_at`, "EXPECTED_RESULT")
})

test_that("nmfs_project_name", {
  # tests for the property `nmfs_project_name` (character)
  # Name of the project/survey under the National Marine Fisheries Service (NMFS) for which the data was collected.

  # uncomment below to test the property
  #expect_equal(model.instance$`nmfs_project_name`, "EXPECTED_RESULT")
})

test_that("vessel_track_geom", {
  # tests for the property `vessel_track_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`vessel_track_geom`, "EXPECTED_RESULT")
})

test_that("actual_station_code", {
  # tests for the property `actual_station_code` (character)
  # Unique identifier for the sampling site visited. For the West Coast Groundfish Bottom Trawl Shelf/Slope Survey, sites follow a gridded pattern. Site codes incrementing sequentially by one from North to South and West to East, with the site furthest to the North starting at 4039 and the site furthest to the south ending at 23399. Most site codes are integers, but present as text data types to accommodate historical formats which included alphanumeric values. Historical site splits are represented by floating point numbers (site 44444 split to 44444.1 and 44444.2). The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_code`, "EXPECTED_RESULT")
})

test_that("started_haulback_at", {
  # tests for the property `started_haulback_at` (character)
  # when winches are started and haulback of the net begins. \&quot;Sampling\&quot; / \&quot;fishing\&quot; for the tow may continue, as the footrope is likely to stay in contact with the bottom for a period of time after haulback begins. UTC Date and time with timezone offset following in ISO 8601 (&#x60;YYYY-MM-DD HH:MM:SS+00&#x60;). Timestamp is to seconds precision (no fractional seconds).

  # uncomment below to test the property
  #expect_equal(model.instance$`started_haulback_at`, "EXPECTED_RESULT")
})

test_that("target_station_code", {
  # tests for the property `target_station_code` (character)
  # Unique identifier for the sampling site visited. For the West Coast Groundfish Bottom Trawl Shelf/Slope Survey, sites follow a gridded pattern. Site codes incrementing sequentially by one from North to South and West to East, with the site furthest to the North starting at 4039 and the site furthest to the south ending at 23399. Most site codes are integers, but present as text data types to accommodate historical formats which included alphanumeric values. Historical site splits are represented by floating point numbers (site 44444 split to 44444.1 and 44444.2). The \&quot;target\&quot; sampling site designation indicates that the site was the target for sampling for the particular operation. The \&quot;target\&quot; sampling site designation indicates that the site was the target for sampling for the particular operation. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to the \&quot;best\&quot; preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`target_station_code`, "EXPECTED_RESULT")
})

test_that("tow_sequence_number", {
  # tests for the property `tow_sequence_number` (integer)
  # Sequential number incrementing by one for each tow from the same vessel by year.

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_sequence_number`, "EXPECTED_RESULT")
})

test_that("wave_direction_code", {
  # tests for the property `wave_direction_code` (character)
  # Direction of waves during operation.

  # uncomment below to test the property
  #expect_equal(model.instance$`wave_direction_code`, "EXPECTED_RESULT")
})

test_that("best_tow_latitude_dd", {
  # tests for the property `best_tow_latitude_dd` (character)
  # Latitude of the single point in space that best represents where the tow sampling took place. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_latitude_dd`, "EXPECTED_RESULT")
})

test_that("swell_direction_code", {
  # tests for the property `swell_direction_code` (character)
  # Direction of swell during operation.

  # uncomment below to test the property
  #expect_equal(model.instance$`swell_direction_code`, "EXPECTED_RESULT")
})

test_that("tow_performance_name", {
  # tests for the property `tow_performance_name` (character)
  # Descriptive name of the tow performance status.

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_performance_name`, "EXPECTED_RESULT")
})

test_that("best_tow_longitude_dd", {
  # tests for the property `best_tow_longitude_dd` (character)
  # Longitude of the single point in space that best represents where the tow sampling took place. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_longitude_dd`, "EXPECTED_RESULT")
})

test_that("total_catch_weight_kg", {
  # tests for the property `total_catch_weight_kg` (numeric)
  # The aggregate total weight of the catch for the tow, measured in kg.

  # uncomment below to test the property
  #expect_equal(model.instance$`total_catch_weight_kg`, "EXPECTED_RESULT")
})

test_that("best_tow_location_geom", {
  # tests for the property `best_tow_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_location_geom`, "EXPECTED_RESULT")
})

test_that("field_party_chief_name", {
  # tests for the property `field_party_chief_name` (character)
  # The operation&#39;s Field Party Chief abbreviated as FPC. The FPC leads all survey sampling and serves as the primary point of contact for data collection methods and operations while at sea.

  # uncomment below to test the property
  #expect_equal(model.instance$`field_party_chief_name`, "EXPECTED_RESULT")
})

test_that("on_bottom_salinity_psu", {
  # tests for the property `on_bottom_salinity_psu` (numeric)
  # water salinity measured in practical salinity units (PSUs).

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_salinity_psu`, "EXPECTED_RESULT")
})

test_that("seafloor_area_swept_ha", {
  # tests for the property `seafloor_area_swept_ha` (numeric)
  # Estimated two-dimensional seafloor area swept during the tow. This metric serves as the denominator for CPUE for species caught (weight (kg) / area swepth). This metric is derived using the following calcultion: derived net wing spread (m) X estimated distance fished (m) / 10000 &#x3D; hectares swept.

  # uncomment below to test the property
  #expect_equal(model.instance$`seafloor_area_swept_ha`, "EXPECTED_RESULT")
})

test_that("seafloor_area_swept_km2", {
  # tests for the property `seafloor_area_swept_km2` (numeric)
  # Estimated two-dimensional seafloor area swept during the tow. This metric serves as the denominator for CPUE for species caught (weight (kg) / area swepth). This metric is derived using the following calcultion: derived net wing spread (m) X estimated distance fished (m) / 1000000 &#x3D; km2 swept.

  # uncomment below to test the property
  #expect_equal(model.instance$`seafloor_area_swept_km2`, "EXPECTED_RESULT")
})

test_that("tow_performance_factors", {
  # tests for the property `tow_performance_factors` (object)
  # JSON array of the recorded tow performance factors, and if they contributed to the tow being marked as unsatifactory.

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_performance_factors`, "EXPECTED_RESULT")
})

test_that("on_bottom_elapsed_time_s", {
  # tests for the property `on_bottom_elapsed_time_s` (integer)
  # Total time the net was on the seafloor in seconds.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_elapsed_time_s`, "EXPECTED_RESULT")
})

test_that("data_readiness_level_code", {
  # tests for the property `data_readiness_level_code` (character)
  # The code representing the data readiness level (Data Readiness Index). Readiness levels classify data across a spectrum from raw field collection to fully validated, analysis-ready products, and can be applied at the most granular level possible (entire datasets or specific row subsets).    Values include:  * **&#x60;L0&#x60; (RAW):** Unaltered sensor or field output. Contains noise and errors. Intended for technical diagnostics and engineering review.  * **&#x60;L1&#x60; (PRELIMINARY):** Ingested and schema-validated. Technical QC complete; Scientific PI review pending. Intended for in-season pulse checks and preliminary trends.  * **&#x60;L2&#x60; (VERIFIED):** Finalized after Scientific PI Review and QA/QC audits. Intended for authoritative Stock Assessments and publication.  * **&#x60;L3&#x60; (HARMONIZED):** Integrated across multi-year programs or disparate surveys using standard taxonomies and units.  * **&#x60;L4&#x60; (DERIVED):** High-value analytic products, aggregations (e.g., CPUE indices), or model-based spatial grids.

  # uncomment below to test the property
  #expect_equal(model.instance$`data_readiness_level_code`, "EXPECTED_RESULT")
})

test_that("direction_to_current_name", {
  # tests for the property `direction_to_current_name` (character)
  # Direction of the vessel relative to the current.

  # uncomment below to test the property
  #expect_equal(model.instance$`direction_to_current_name`, "EXPECTED_RESULT")
})

test_that("on_bottom_gear_track_geom", {
  # tests for the property `on_bottom_gear_track_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_gear_track_geom`, "EXPECTED_RESULT")
})

test_that("bottom_trawl_operation_key", {
  # tests for the property `bottom_trawl_operation_key` (character)
  # A 12-character numeric unique identifier for a West Coast Groundfish Bottom Trawl sampling operation.     It is constructed by concatenating key operational attributes into a single string. For example, the operation key **&#x60;202203020001&#x60;** breaks down as follows:    * **Survey Year (Digits 1-4):** The 4-digit year (YYYY) of sampling (e.g., &#x60;2022&#x60;).  * **Operation Type (Digits 5-6):** The 2-digit code representing the survey operation type (e.g., &#x60;03&#x60;).  * **Vessel ID (Digits 7-9):** The 3-digit, zero-padded identifier for the participating vessel (e.g., &#x60;020&#x60;).  * **Operation Increment (Digits 10-12):** The 3-digit, zero-padded sequential operation increment (e.g., &#x60;001&#x60;).

  # uncomment below to test the property
  #expect_equal(model.instance$`bottom_trawl_operation_key`, "EXPECTED_RESULT")
})

test_that("on_bottom_seafloor_depth_m", {
  # tests for the property `on_bottom_seafloor_depth_m` (numeric)
  # the depth of the seafloor to sea surface surface in meters.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_seafloor_depth_m`, "EXPECTED_RESULT")
})

test_that("vertebrate_catch_weight_kg", {
  # tests for the property `vertebrate_catch_weight_kg` (numeric)
  # The aggregate total weight of all vertebrates caught on tow, measured in kg.

  # uncomment below to test the property
  #expect_equal(model.instance$`vertebrate_catch_weight_kg`, "EXPECTED_RESULT")
})

test_that("actual_station_centroid_key", {
  # tests for the property `actual_station_centroid_key` (integer)
  # A composite spatial key that uniquely identifies the centroid of a WCGBTS (West Coast Groundfish Bottom Trawl Survey) sampling station grid cell.     This key is a fixed 8-character string constructed by converting decimal degree coordinates into Degrees and Decimal Minutes (DDM), stripping away negative signs and truncating specific digits to create a consistent spatial identifier.    ### Component Breakdown  The 8-character format strictly follows the pattern **&#x60;[Lat Degrees][Lat Minutes][Lon Degrees][Lon Minutes]&#x60;**:    * **Latitude Degrees (2 characters):** The whole number of the decimal latitude (e.g., &#x60;43.58&#x60; becomes &#x60;43&#x60;).  * **Latitude Minutes (2 characters):** The decimal remainder of the latitude multiplied by 60 and rounded to the nearest whole number (e.g., &#x60;0.58139 * 60 &#x3D; 34.88&#x60;, which rounds to &#x60;35&#x60;).  * **Longitude Degrees (2 characters):** The whole number of the longitude, ignoring the negative sign (West) and dropping the leading hundreds place (e.g., &#x60;-124.61&#x60; becomes &#x60;24&#x60;).  * **Longitude Minutes (2 characters):** The decimal remainder of the longitude multiplied by 60 and rounded to the nearest whole number (e.g., &#x60;0.61465 * 60 &#x3D; 36.87&#x60;, which rounds to &#x60;37&#x60;).    &gt; **Example:** A grid cell centroid located at decimal coordinates **&#x60;43.58139678, -124.61465068&#x60;** results in the centroid key **&#x60;43352437&#x60;**.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_centroid_key`, "EXPECTED_RESULT")
})

test_that("actual_station_history_json", {
  # tests for the property `actual_station_history_json` (object)
  # JSON listing array of historical activation/deactivations of the actual station sampled. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_history_json`, "EXPECTED_RESULT")
})

test_that("doors_up_vessel_latitude_dd", {
  # tests for the property `doors_up_vessel_latitude_dd` (character)
  # Latitude of the vessel when the trawl doors are first visible at the sea surface from the deck/wheelhouse. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_up_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("on_bottom_distance_fished_m", {
  # tests for the property `on_bottom_distance_fished_m` (numeric)
  # Estimated distance in meters that the net was in contact with the bottom and fishing. This metric contributes directly to area swept and resulting CPUE (distance fished X derived net wing spread &#x3D; area swept).

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_distance_fished_m`, "EXPECTED_RESULT")
})

test_that("on_bottom_net_door_spread_m", {
  # tests for the property `on_bottom_net_door_spread_m` (numeric)
  # the spread distance in meters of the trawl doors. While fishing on the WCGBTS Shelf/Slope survey this metric typically ranges from 30-50 meters, and may be used to predict corresponding wing spread for the tow if no wing spread is available.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_net_door_spread_m`, "EXPECTED_RESULT")
})

test_that("on_bottom_net_wing_spread_m", {
  # tests for the property `on_bottom_net_wing_spread_m` (numeric)
  # the spread distance in meters of the trawl net wings. This value is typically used as the best proxy for the width of the area covered by the net while fishing.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_net_wing_spread_m`, "EXPECTED_RESULT")
})

test_that("doors_out_vessel_latitude_dd", {
  # tests for the property `doors_out_vessel_latitude_dd` (character)
  # Latitude of the vessel when the trawl doors are fully out, wire is wire fully deployed, and winch is stopped. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_out_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("doors_set_vessel_latitude_dd", {
  # tests for the property `doors_set_vessel_latitude_dd` (character)
  # Latitude of the vessel when the trawl doors were set after gear was deployed. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_set_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("doors_up_vessel_longitude_dd", {
  # tests for the property `doors_up_vessel_longitude_dd` (character)
  # Longitude of the vessel when the trawl doors are first visible at the sea surface from the deck/wheelhouse. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_up_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("invertebrate_catch_weight_kg", {
  # tests for the property `invertebrate_catch_weight_kg` (numeric)
  # The aggregate total weight of all invertebrates caught on tow, measured in kg.

  # uncomment below to test the property
  #expect_equal(model.instance$`invertebrate_catch_weight_kg`, "EXPECTED_RESULT")
})

test_that("doors_out_vessel_longitude_dd", {
  # tests for the property `doors_out_vessel_longitude_dd` (character)
  # Longitude of the vessel when the trawl doors are fully out, wire is wire fully deployed, and winch is stopped. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_out_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("doors_set_vessel_longitude_dd", {
  # tests for the property `doors_set_vessel_longitude_dd` (character)
  # Longitude of the vessel when the trawl doors were set after gear was deployed. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_set_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("doors_up_vessel_location_geom", {
  # tests for the property `doors_up_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_up_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("on_bottom_water_pressure_dbar", {
  # tests for the property `on_bottom_water_pressure_dbar` (numeric)
  # water pressure measured in decibars (dbar).

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_water_pressure_dbar`, "EXPECTED_RESULT")
})

test_that("on_bottom_water_temperature_c", {
  # tests for the property `on_bottom_water_temperature_c` (numeric)
  # seafloor water temperature measured in degrees Celsius.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_water_temperature_c`, "EXPECTED_RESULT")
})

test_that("on_bottom_water_turbidity_ntu", {
  # tests for the property `on_bottom_water_turbidity_ntu` (numeric)
  # turbidity measured in Nephelometric Turbidity Units (NTUs).

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_water_turbidity_ntu`, "EXPECTED_RESULT")
})

test_that("doors_out_vessel_location_geom", {
  # tests for the property `doors_out_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_out_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("doors_set_vessel_location_geom", {
  # tests for the property `doors_set_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`doors_set_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_gear_latitude_dd", {
  # tests for the property `net_on_bottom_gear_latitude_dd` (character)
  # Latitude of the gear/net when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_gear_latitude_dd`, "EXPECTED_RESULT")
})

test_that("on_bottom_net_headrope_depth_m", {
  # tests for the property `on_bottom_net_headrope_depth_m` (numeric)
  # the depth in meters of the net&#39;s headrope from the sea surface. The sum of this metric and the headrope&#39;s height is often used to estimate total seafloor depth.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_net_headrope_depth_m`, "EXPECTED_RESULT")
})

test_that("tow_started_vessel_latitude_dd", {
  # tests for the property `tow_started_vessel_latitude_dd` (character)
  # Latitude of the vessel when the tow was first initiated and gear was deployed. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_started_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("is_tow_performance_satisfactory", {
  # tests for the property `is_tow_performance_satisfactory` (character)
  # Flag indicating if the tow was performed according to protocols.

  # uncomment below to test the property
  #expect_equal(model.instance$`is_tow_performance_satisfactory`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_gear_latitude_dd", {
  # tests for the property `net_off_bottom_gear_latitude_dd` (character)
  # Latitude of the gear/net when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_gear_latitude_dd`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_gear_longitude_dd", {
  # tests for the property `net_on_bottom_gear_longitude_dd` (character)
  # Longitude of the gear/net when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_gear_longitude_dd`, "EXPECTED_RESULT")
})

test_that("on_bottom_net_headrope_height_m", {
  # tests for the property `on_bottom_net_headrope_height_m` (numeric)
  # the distance in meters between the net&#39;s headrope and the seafloor. The sum of this metric and the headrope&#39;s depth is often used to estimate total seafloor depth.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_net_headrope_height_m`, "EXPECTED_RESULT")
})

test_that("tow_started_vessel_longitude_dd", {
  # tests for the property `tow_started_vessel_longitude_dd` (character)
  # Longitude of the vessel when the tow was first initiated and gear was deployed. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_started_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("actual_station_deactivation_year", {
  # tests for the property `actual_station_deactivation_year` (integer)
  # The year YYYY when the actual station sampled was last deactivated, if the site is currently inactive. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_deactivation_year`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_gear_longitude_dd", {
  # tests for the property `net_off_bottom_gear_longitude_dd` (character)
  # Longitude of the gear/net when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_gear_longitude_dd`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_gear_location_geom", {
  # tests for the property `net_on_bottom_gear_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_gear_location_geom`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_vessel_latitude_dd", {
  # tests for the property `net_on_bottom_vessel_latitude_dd` (character)
  # Latitude of the vessel when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("tow_started_vessel_location_geom", {
  # tests for the property `tow_started_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_started_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("actual_station_depth_stratum_name", {
  # tests for the property `actual_station_depth_stratum_name` (character)
  # Name of the depth stratum that the sampling site falls into. Sampling on the West Coast Groundfish Bottom Trawl Shelf/Slope Survey follows a randomly stratified design, with sampling sites falling into one of three depth strata: 30-100 fathoms, 100-300 fathoms, and 300-700 fathoms. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_depth_stratum_name`, "EXPECTED_RESULT")
})

test_that("data_readiness_level_display_name", {
  # tests for the property `data_readiness_level_display_name` (character)
  # The formatted display name representing the data readiness level, combining the level code and its status label.    Values include:  * **&#x60;L0 - RAW&#x60;:** Unaltered sensor or field output containing noise and errors.  * **&#x60;L1 - PRELIMINARY&#x60;:** Ingested and schema-validated, pending Scientific PI review.  * **&#x60;L2 - VERIFIED&#x60;:** Finalized after Scientific PI Review and QA/QC audits.  * **&#x60;L3 - HARMONIZED&#x60;:** Integrated across multi-year programs or disparate surveys.  * **&#x60;L4 - DERIVED&#x60;:** High-value analytic products, aggregations, or model-based spatial grids.

  # uncomment below to test the property
  #expect_equal(model.instance$`data_readiness_level_display_name`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_gear_location_geom", {
  # tests for the property `net_off_bottom_gear_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_gear_location_geom`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_vessel_latitude_dd", {
  # tests for the property `net_off_bottom_vessel_latitude_dd` (character)
  # Latitude of the vessel when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_vessel_longitude_dd", {
  # tests for the property `net_on_bottom_vessel_longitude_dd` (character)
  # Longitude of the vessel when the footrope initially makes contact with the bottom, marking the start of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("on_bottom_water_density_kg_per_m3", {
  # tests for the property `on_bottom_water_density_kg_per_m3` (numeric)
  # water density measured in kg/m3.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_water_density_kg_per_m3`, "EXPECTED_RESULT")
})

test_that("started_haulback_gear_latitude_dd", {
  # tests for the property `started_haulback_gear_latitude_dd` (character)
  # Latitude of the gear/net when winches are started and haulback of the net begins. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`started_haulback_gear_latitude_dd`, "EXPECTED_RESULT")
})

test_that("is_actual_station_currently_active", {
  # tests for the property `is_actual_station_currently_active` (character)
  # Boolean indicating if the actual station sampled is currently active. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`is_actual_station_currently_active`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_vessel_longitude_dd", {
  # tests for the property `net_off_bottom_vessel_longitude_dd` (character)
  # Longitude of the vessel when the footrope loses contact with the bottom after haulback has begun, marking the end of \&quot;sampling\&quot; / \&quot;fishing\&quot; for the tow. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("net_on_bottom_vessel_location_geom", {
  # tests for the property `net_on_bottom_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`net_on_bottom_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("started_haulback_gear_longitude_dd", {
  # tests for the property `started_haulback_gear_longitude_dd` (character)
  # Longitude of the gear/net when winches are started and haulback of the net begins. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`started_haulback_gear_longitude_dd`, "EXPECTED_RESULT")
})

test_that("net_off_bottom_vessel_location_geom", {
  # tests for the property `net_off_bottom_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`net_off_bottom_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("on_bottom_dissolved_oxygen_ml_per_l", {
  # tests for the property `on_bottom_dissolved_oxygen_ml_per_l` (numeric)
  # dissolved oxygen measured in ml/L.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_dissolved_oxygen_ml_per_l`, "EXPECTED_RESULT")
})

test_that("started_haulback_gear_location_geom", {
  # tests for the property `started_haulback_gear_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`started_haulback_gear_location_geom`, "EXPECTED_RESULT")
})

test_that("started_haulback_vessel_latitude_dd", {
  # tests for the property `started_haulback_vessel_latitude_dd` (character)
  # Latitude of the vessel when winches are started and haulback of the net begins. Latitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`started_haulback_vessel_latitude_dd`, "EXPECTED_RESULT")
})

test_that("tow_sea_surface_water_temperature_c", {
  # tests for the property `tow_sea_surface_water_temperature_c` (numeric)
  # Mean water temperature recorded at the sea surface during the extent of the tow. Temperature is typically recorded  In recent years this metric is typically collected via a hull-mounted Seabird Scientific SBE39plus temperature recorder,  with real-time data streamed via serial protocol into the wheelhouse for an average calculation.

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_sea_surface_water_temperature_c`, "EXPECTED_RESULT")
})

test_that("actual_station_latitude_stratum_name", {
  # tests for the property `actual_station_latitude_stratum_name` (character)
  # Name of the latitude stratum that the sampling site falls into. Sampling on the West Coast Groundfish Bottom Trawl Shelf/Slope Survey follows a randomly stratified design, with sampling sites falling into one of two latitude strata: North of Point Conception (&gt;34°30&#39;N) or South of Point Conception (&lt;34°30&#39;N). The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_latitude_stratum_name`, "EXPECTED_RESULT")
})

test_that("nonspecific_organics_catch_weight_kg", {
  # tests for the property `nonspecific_organics_catch_weight_kg` (numeric)
  # The aggregate total weight of nonspecific organic catch samples caught on tow, measured in kg. To date this category includes the following: gelatinous material unident., unsorted shab, decomposed fish, Echinoidea (crushed urchin), empty bivalve shells, empty gastropod shells, nonspecific egg-case unident.

  # uncomment below to test the property
  #expect_equal(model.instance$`nonspecific_organics_catch_weight_kg`, "EXPECTED_RESULT")
})

test_that("started_haulback_vessel_longitude_dd", {
  # tests for the property `started_haulback_vessel_longitude_dd` (character)
  # Longitude of the vessel when winches are started and haulback of the net begins. Longitude presented as decimal degrees with up to eight points of precision.

  # uncomment below to test the property
  #expect_equal(model.instance$`started_haulback_vessel_longitude_dd`, "EXPECTED_RESULT")
})

test_that("started_haulback_vessel_location_geom", {
  # tests for the property `started_haulback_vessel_location_geom` (GeoJSON)

  # uncomment below to test the property
  #expect_equal(model.instance$`started_haulback_vessel_location_geom`, "EXPECTED_RESULT")
})

test_that("on_bottom_water_conductivity_ml_per_m3", {
  # tests for the property `on_bottom_water_conductivity_ml_per_m3` (numeric)
  # water conductivity.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_water_conductivity_ml_per_m3`, "EXPECTED_RESULT")
})

test_that("tow_sea_surface_fluorescence_mg_per_m3", {
  # tests for the property `tow_sea_surface_fluorescence_mg_per_m3` (numeric)
  # water fluorescence measured in ml/m3 (dbar).

  # uncomment below to test the property
  #expect_equal(model.instance$`tow_sea_surface_fluorescence_mg_per_m3`, "EXPECTED_RESULT")
})

test_that("was_actual_station_active_when_sampled", {
  # tests for the property `was_actual_station_active_when_sampled` (character)
  # Boolean indicating if the actual station was active at the time it was sampled. The \&quot;best\&quot; sampling site designation indicates that the single summarized tow/haul location falls within this site boundary. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to this preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`was_actual_station_active_when_sampled`, "EXPECTED_RESULT")
})

test_that("was_target_station_active_when_sampled", {
  # tests for the property `was_target_station_active_when_sampled` (character)
  # Boolean indicating if the target station was active at the time of sampling. The \&quot;target\&quot; sampling site designation indicates that the site was the target for sampling for the particular operation. The \&quot;target\&quot; site may diverge from the \&quot;best\&quot; in the event that the tow operation carries the sampling outside of the intended site boundary, and the tow is then actually assigned to the \&quot;best\&quot; preferred geolocated site.

  # uncomment below to test the property
  #expect_equal(model.instance$`was_target_station_active_when_sampled`, "EXPECTED_RESULT")
})

test_that("best_tow_location_calculation_method_name", {
  # tests for the property `best_tow_location_calculation_method_name` (character)
  # Calculation method used to determine the single \&quot;best\&quot; location for a tow.  For Shelf/Slope tows, the preferred and primary method to date is to identify the  median latitude and median longitude values of the on-bottom estimated gear track, and combine to derive the best location.  Only in the absence of data  used to estimate the gear track is an alternative method typically used.

  # uncomment below to test the property
  #expect_equal(model.instance$`best_tow_location_calculation_method_name`, "EXPECTED_RESULT")
})

test_that("actual_station_current_deactivation_reasons", {
  # tests for the property `actual_station_current_deactivation_reasons` (character)
  # Comma-separated list of current reasons that a station is listed as inactive.  Value should be null unless the station is currently inactive.

  # uncomment below to test the property
  #expect_equal(model.instance$`actual_station_current_deactivation_reasons`, "EXPECTED_RESULT")
})

test_that("on_bottom_seafloor_depth_calculation_method_name", {
  # tests for the property `on_bottom_seafloor_depth_calculation_method_name` (character)
  # Name of the calculation method used to derive the best seafloor depth while the net was fishing on the bottom.

  # uncomment below to test the property
  #expect_equal(model.instance$`on_bottom_seafloor_depth_calculation_method_name`, "EXPECTED_RESULT")
})
