# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BottomTrawlBottomTrawlShelfSlopeVessels")

model_instance <- BottomTrawlBottomTrawlShelfSlopeVessels$new()

test_that("label", {
  # tests for the property `label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("survey_years", {
  # tests for the property `survey_years` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`survey_years`, "EXPECTED_RESULT")
})

test_that("nmfs_project_names", {
  # tests for the property `nmfs_project_names` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nmfs_project_names`, "EXPECTED_RESULT")
})
