#Add repo-base sources to base-os
ARG IMAGE_DOCKER_PREFIX="unknown"
ARG TZ="America/Los_Angeles"
ARG JOB_TYPE="unknown"

ARG PARENT_IMAGE=${IMAGE_DOCKER_PREFIX}/repo-base:${JOB_TYPE}
FROM ${PARENT_IMAGE}

#Need to do the above to refresh build args, then store in ENV
#https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

ARG BUILD_DATE="unknown"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_HOST="unknown"
ENV BUILD_HOST=${BUILD_HOST}
ARG CONTEXT="unknown"
ENV CONTEXT=${CONTEXT}
ARG DOCKER_FILE="unknown"
ENV DOCKER_FILE=${DOCKER_FILE}
ARG GIT_BRANCH="unknown"
ENV GIT_BRANCH=${GIT_BRANCH}
ARG GIT_COMMIT="unknown"
ENV GIT_COMMIT=${GIT_COMMIT}
ARG GIT_ORG="unknown"
ENV GIT_ORG=${GIT_ORG}
ARG GIT_REPO="unknown"
ENV GIT_REPO=${GIT_REPO}
ARG GIT_URL="unknown"
ENV GIT_URL=${GIT_URL}
ARG IMAGE_DOCKER_PREFIX="unknown"
ENV IMAGE_DOCKER_PREFIX=${IMAGE_DOCKER_PREFIX}
ARG IMAGE_NAME="unknown"
ENV IMAGE_NAME=${IMAGE_NAME}
ARG JOB_TYPE="unknown"
ENV JOB_TYPE=${JOB_TYPE}
ARG PIPELINE_BRANCH="unknown"
ENV PIPELINE_BRANCH=${PIPELINE_BRANCH}
ARG PIPELINE_COMMIT="unknown"
ENV PIPELINE_COMMIT=${PIPELINE_COMMIT}
ARG PIPELINE_DOCKER_PREFIX="unknown"
ENV PIPELINE_DOCKER_PREFIX=${PIPELINE_DOCKER_PREFIX}
ARG PIPELINE_REPO="unknown"
ENV PIPELINE_REPO=${PIPELINE_REPO}
ARG PIPELINE_URL="unknown"
ENV PIPELINE_URL=${PIPELINE_URL}

ARG SERVICE_NAME="template-tools"
ENV SERVICE_NAME=${SERVICE_NAME}
ARG TZ="America/Los_Angeles"
ENV TZ=${TZ}

# `Docker inspect` can be used to view image Labels.
LABEL Maintainer="At Sea Data Team:Northwest Fisheries Science Center"
LABEL Contact="nmfs.nwfsc.fram.data.team@noaa.gov"
LABEL description="Docker image to run tools and scripts under ${GIT_REPO}"
LABEL parent_image="${PARENT_IMAGE}"
LABEL source="${GIT_URL}"
LABEL branch="${GIT_BRANCH}"
LABEL commit="${GIT_COMMIT}"
LABEL version="3.0"
LABEL author="Stephen Montsaroff"

#Git images for repos (XXX/repo-base) are stored under GIT_REPO
#Derived images (for services) since there are multiple possible are
RUN mv -v /root/${GIT_REPO} /root/${SERVICE_NAME}
COPY ./ /root/${SERVICE_NAME}/

#ADD .${SERVICE_NAME}-${JOB_TYPE}-upload_dir /root/.upload_dir
#RUN if [ -f /root/.upload_dir/config.sh ];then chmod a+x /root/.upload_dir/config.sh ;fi

WORKDIR /root/${SERVICE_NAME}/.github/scripts

#RUN cp -p /root/.upload_dir/* . && . ./config.sh
#RUN mkdir -p ./config
#RUN mv -v  ./*.key  ./dbConfig.json ./config

#add export configuration to make deployment easier
RUN mkdir -p /root/export
RUN ln -s /root/${SERVICE_NAME} /root/export/${SERVICE_NAME}
WORKDIR /root/export/${SERVICE_NAME}

ENTRYPOINT ["bash", "--login","-c"]
CMD ["bash"]

