#Add repo-base sources to base-os
ARG PIPELINE_DOCKER_PREFIX="unknown"
ARG TZ="America/Los_Angeles"
ARG JOB_TYPE="unknown"

ARG PARENT_IMAGE=${PIPELINE_DOCKER_PREFIX}/base-os:${JOB_TYPE}
FROM ${PARENT_IMAGE}

#Need to do the above to refresh build args, then store in ENV
#https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

ARG BUILD_DATE="unknown"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_HOST="unknown"
ENV BUILD_HOST=${BUILD_HOST}
ARG CONTEXT="unknown"
ENV CONTEXT=${CONTEXT}
ARG DOCKER_FILE="unknown"
ENV DOCKER_FILE=${DOCKER_FILE}
ARG GIT_BRANCH="unknown"
ENV GIT_BRANCH=${GIT_BRANCH}
ARG GIT_COMMIT="unknown"
ENV GIT_COMMIT=${GIT_COMMIT}
ARG	GIT_ORG="unknown"
ENV GIT_ORG=${GIT_ORG}
ARG GIT_REPO="unknown"
ENV GIT_REPO=${GIT_REPO}
ARG GIT_URL="unknown"
ENV GIT_URL=${GIT_URL}
ARG IMAGE_DOCKER_PREFIX="unknown"
ENV IMAGE_DOCKER_PREFIX=${IMAGE_DOCKER_PREFIX}
ARG IMAGE_NAME="unknown"
ENV IMAGE_NAME=${IMAGE_NAME}
ARG JOB_TYPE="unknown"
ENV JOB_TYPE=${JOB_TYPE}
ARG PIPELINE_BRANCH="unknown"
ENV PIPELINE_BRANCH=${PIPELINE_BRANCH}
ARG PIPELINE_COMMIT="unknown"
ENV PIPELINE_COMMIT=${PIPELINE_COMMIT}
ARG PIPELINE_DOCKER_PREFIX="unknown"
ENV PIPELINE_DOCKER_PREFIX=${PIPELINE_DOCKER_PREFIX}
ARG PIPELINE_REPO="unknown"
ENV PIPELINE_REPO=${PIPELINE_REPO}
ARG PIPELINE_URL="unknown"
ENV PIPELINE_URL=${PIPELINE_URL}

ARG SERVICE_NAME="asdt-pipeline/repo-base"
ENV SERVICE_NAME=${SERVICE_NAME}
ARG TZ="America/Los_Angeles"
ENV TZ=${TZ}

# `Docker inspect` can be used to view image Labels.
LABEL Maintainer="At Sea Data Team:Northwest Fisheries Science Center"
LABEL Contact="nmfs.nwfsc.fram.data.team@noaa.gov"
LABEL description="Docker image to run standard repository defined in ${GIT_REPO}"
LABEL parent_image="${PARENT_IMAGE}"
LABEL source="${GIT_URL}"
LABEL branch="${GIT_BRANCH}"
LABEL commit="${GIT_COMMIT}"
LABEL version="3.0"
LABEL author="Stephen Montsaroff"

COPY .  /root/${GIT_REPO}        
WORKDIR /root/${GIT_REPO}/
RUN chmod -R u=rwX,g=rwX,o= .

ENTRYPOINT ["bash", "--login","-c"]
#CMD ["/root/motd.sh"]
CMD ["bash"]


