[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nwfsc-data-catalog"
version = "0.1.8"
description = "Public Python client for the NWFSC Data Catalog API"
requires-python = ">=3.9"
dependencies = [
    "urllib3 >= 1.25.3",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.0.0",
    "typing-extensions >= 4.7.1",
    "pandas >= 2.0.0",      # Hard dependency for .read_ and .to_dataframe()
    "mcp>=1.0.0,<2.0.0"
]

[project.scripts]
nwfsc-mcp = "nwfsc_data_catalog.mcp_server:main"

[project.optional-dependencies]
# Install via: pip install nwfsc-data-catalog[geo]
geo = [
    "geopandas >= 0.14.0",
    "shapely >= 2.0.0"
]
# Install via: pip install nwfsc-data-catalog[test]
test = [
    "pytest >= 7.0.0",
    "pytest-mock",
    "openapi-spec-validator >= 0.7.1"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
# E: pycodestyle, F: Pyflakes, I: isort
select = ["E", "F", "I"]
ignore = ["E501"] # Ignore long lines in generated code if necessary

[tool.ruff.format]
quote-style = "double"
indent-style = "space"